### ISSUE TITLE
please tag a new release version for iLCsoft release

### ISSUE THREAD

**Issue by gaede** [FCALSW/FCalClusterer#28]
!!!IMPORTANT!!!: To facilitate faster and easier response to your issue please provide in addition to the description of the issue also the following information

 - OS version: e.g. SLC6
 - Compiler version: e.g GCC 6.2
 - Package version: tag, commit ID, CVMFS release or GitHub branch
 - Reproduced by: exact steps to reproduce the problem: checkout, setup environment (iLCSoft release), cmake, build, run...
 - Input: link to input files if applicable
 - Output: full build and run log output
 - Goal: A short description of what you are trying to achieve

**Comment by gaede** [comment]
@sailer can you please make a release tag for the FCalClusterer - the latest tag does not build w/ current iLCSoft (DD4hep).

**Comment by andresailer** [comment]
Tagged https://github.com/FCALSW/FCalClusterer/releases/tag/v00-06
