### ISSUE TITLE
Need help with DrawBeamCalFromDD4hep processor

### ISSUE THREAD

**Issue by StrahinjaLukic** [FCALSW/FCalClusterer#37]
I am trying to run DrawBeamCalFromDD4hep processor with some ILD detector models. I am running into an exception "Attempt to access invalid object of type dd4hep::DetElementObject" (full output attached below). 

Thanks for any hints. Let me know if I can provide more information...

 - OS version: SLC6
 - Compiler version:  GCC 4.9
 - Package version: ilcsoft v01-19-05, FCalClusterer v00-06
 - Reproduced by: ...
 - Input: 
[FCalClusterer.xml.zip](https://github.com/FCALSW/FCalClusterer/files/1668483/FCalClusterer.xml.zip)
 - Output: 
[drawBCal.out.zip](https://github.com/FCALSW/FCalClusterer/files/1668488/drawBCal.out.zip)

**Comment by andresailer** [comment]
Hi Strahinja, can you try the patch from #38 I think that should fix things

**Comment by StrahinjaLukic** [comment]
That did it! Thanks.
