### ISSUE TITLE
Reconstruction in the LumiCal with eepairs

### ISSUE THREAD

**Issue by rete** [FCALSW/FCalClusterer#47]
Hi @andresailer !

I'm looking at the BeamCalReco and background tunning for ILD. For the moment, by following the documentation in #45 , I almost got the BeamCalReco re-tuned. I saw you have made a PR (#46) to make it also possible for the LumiCal. 
- Q : Is there anything to re-tune on this side ?

The LumiCal collection is [passed to PandoraPFA](https://github.com/iLCSoft/ILDConfig/blob/master/StandardConfig/production/ParticleFlow/PandoraPFA.xml#L13) for the moment. 
- Q : By the PR #46 , do you mean we could also run a standalone reconstruction in the LumiCal with a pair background overlay like for the BeamCal ?

**Comment by andresailer** [comment]
> Q: Is there anything to re-tune on this side ?

Can you be more specific what you are talking about with "this side"? Is this for the BeamCal or LumiCal? Re-tune with respect to what?

> Q : By the PR #46 , do you mean we could also run a standalone reconstruction in the LumiCal with a pair background overlay like for the BeamCal ?

The use the BeamCalClusterReco for LumiCal was implemented in #36. The creation of the background files for LumiCal was added in #46.

**Comment by rete** [comment]
Sorry for the delay. 

> Can you be more specific what you are talking about with "this side"? Is this for the BeamCal or LumiCal? Re-tune with respect to what?
I thought about tunning the LumiCal reconstruction with the BeamCalClusterReco processor instead of passing the hits to PandoraPFA. But this would actually requires a detailed study/validation that we can't afford before starting the ILD production.
I close this issue.
